### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by yanboyang713** [guowenping123/hello-people#1]
哈哈哈

**Comment by guowenping123** [comment]
OK~

**Comment by yanboyang713** [comment]
可以关了 @guowenping123

**Comment by guowenping123** [comment]
哦

**Comment by guowenping123** [comment]
你也在看电脑 @yanboyang713

**Comment by yanboyang713** [comment]
>  你也在看电脑 @yanboyang713 

我用的手机

**Comment by guowenping123** [comment]
哈哈哈，有意思，
![0AB94DCA](https://user-images.githubusercontent.com/91422381/146387522-4182063a-9832-417d-856c-e057a186ea24.png)

**Comment by yanboyang713** [comment]
> 哈哈哈，有意思，
> ![0AB94DCA](https://user-images.githubusercontent.com/91422381/146387522-4182063a-9832-417d-856c-e057a186ea24.png)
> 
> 

这就团队合作用的
如果我关了issue是不是就看不到你了？

**Comment by guowenping123** [comment]
哦~那我除了你，我谁也不认识呀~那我找谁开呀？难道只要我搜索到就可以
